2023-01-25 08:09:00,113 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-01-25 08:09:00,117 INFO supervisord started with pid 7
2023-01-25 08:09:01,121 INFO spawned: 'app' with pid 8
2023-01-25 08:09:01,124 INFO spawned: 'nginx' with pid 9
Bottle v0.12.23 server starting up (using WSGIRefServer())...
Listening on http://localhost:5000/
Hit Ctrl-C to quit.

2023-01-25 08:09:02,521 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-01-25 08:09:02,522 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[CTRL] POST /setup
[Time: 25.01.23 08:09:03] [Level: info] id: 98dbf48fedb0e5b4
[Time: 25.01.23 08:09:03] [Level: info] coordinator: True
[Time: 25.01.23 08:09:03] [Level: info] clients: ['98dbf48fedb0e5b4']
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/root/.local/lib/python3.8/site-packages/bottle.py", line 1756, in wrapper
    rv = callback(*a, **ka)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/api/http_ctrl.py", line 21, in ctrl_setup
    app.handle_setup(payload.get('id'), payload.get('coordinator'), payload.get('clients'))
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 162, in handle_setup
    self.log('initial state not found', level=LogLevel.FATAL)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 343, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 25.01.23 08:09:03] [Level: fatal] initial state not found
127.0.0.1 - - [25/Jan/2023 08:09:03] "POST /api/setup HTTP/1.0" 500 751
[CTRL] POST /setup
[Time: 25.01.23 08:09:08] [Level: info] id: 98dbf48fedb0e5b4
[Time: 25.01.23 08:09:08] [Level: info] coordinator: True
[Time: 25.01.23 08:09:08] [Level: info] clients: ['98dbf48fedb0e5b4']
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/root/.local/lib/python3.8/site-packages/bottle.py", line 1756, in wrapper
    rv = callback(*a, **ka)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/api/http_ctrl.py", line 21, in ctrl_setup
    app.handle_setup(payload.get('id'), payload.get('coordinator'), payload.get('clients'))
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 162, in handle_setup
    self.log('initial state not found', level=LogLevel.FATAL)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 343, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 25.01.23 08:09:08] [Level: fatal] initial state not found
127.0.0.1 - - [25/Jan/2023 08:09:08] "POST /api/setup HTTP/1.0" 500 751
[CTRL] POST /setup
[Time: 25.01.23 08:09:17] [Level: info] id: 98dbf48fedb0e5b4
[Time: 25.01.23 08:09:17] [Level: info] coordinator: True
[Time: 25.01.23 08:09:17] [Level: info] clients: ['98dbf48fedb0e5b4']
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/root/.local/lib/python3.8/site-packages/bottle.py", line 1756, in wrapper
    rv = callback(*a, **ka)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/api/http_ctrl.py", line 21, in ctrl_setup
    app.handle_setup(payload.get('id'), payload.get('coordinator'), payload.get('clients'))
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 162, in handle_setup
    self.log('initial state not found', level=LogLevel.FATAL)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 343, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 25.01.23 08:09:17] [Level: fatal] initial state not found
127.0.0.1 - - [25/Jan/2023 08:09:17] "POST /api/setup HTTP/1.0" 500 751
[CTRL] POST /setup
[Time: 25.01.23 08:09:34] [Level: info] id: 98dbf48fedb0e5b4
[Time: 25.01.23 08:09:34] [Level: info] coordinator: True
[Time: 25.01.23 08:09:34] [Level: info] clients: ['98dbf48fedb0e5b4']
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/root/.local/lib/python3.8/site-packages/bottle.py", line 1756, in wrapper
    rv = callback(*a, **ka)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/api/http_ctrl.py", line 21, in ctrl_setup
    app.handle_setup(payload.get('id'), payload.get('coordinator'), payload.get('clients'))
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 162, in handle_setup
    self.log('initial state not found', level=LogLevel.FATAL)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 343, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 25.01.23 08:09:34] [Level: fatal] initial state not found
127.0.0.1 - - [25/Jan/2023 08:09:34] "POST /api/setup HTTP/1.0" 500 751
